# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'. 

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]
        #- job_name: "webapp"
    #static_configs:
      #- targets: ["nginx:8080"]
        #- job_name: "fastify"
    #    metrics_path: "/metrics"
#    static_configs:
#      - targets: ["localhost:3000"]

#remote_write:
#  - url: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
#    basic_auth:
#      username: "2299779"
#      password: "glc_eyJvIjoiMTM2NDU4NyIsIm4iOiJzdGFjay0xMTg3NzY4LWhtLXdyaXRlLXRva2VuIiwiayI6Im8xMzF4MnhQMlBRZUQwSTNBTzQ3QnM3cyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19"

