events {}

http {
    upstream prometheus_backend {
        server prometheus:9090;
    }

    server {
        listen 8080;
        
        location = /basic_status {
            stub_status;
            allow all;
        }

        root /frontend;
        index index.html;
        
        location /metrics {
            proxy_pass http://nginx_exporter:9113/metrics;
        }

        location / {
            try_files $uri /index.html;
        }

        location /api/ {
            proxy_pass http://fastify_backend:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /prometheus/ {
            rewrite ^/prometheus(/.*)$ $1 break;
            proxy_pass http://prometheus_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect / /prometheus/;
        }

        location /grafana/ {
            proxy_pass http://grafana:3000/grafana/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Script-Name /grafana;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect default;
        }
    }
}

